### ISSUE TITLE
Install error: AssertionError: database connection isn't set to UTC

### ISSUE THREAD

**Issue by jedie** [YunoHost-Apps/pyinventory_ynh#62]
```
Warning: Traceback (most recent call last):
Warning:   File "./manage.py", line 15, in <module>
Warning:     main()
Warning:   File "./manage.py", line 11, in main
Warning:     execute_from_command_line(sys.argv)
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
Warning:     utility.execute()
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
Warning:     self.fetch_command(subcommand).run_from_argv(self.argv)
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
Warning:     self.execute(*args, **cmd_options)
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
Warning:     output = self.handle(*args, **options)
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django_yunohost_integration/management/commands/create_superuser.py", line 37, in handle
Warning:     user = User.objects.filter(username=username).first()
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/db/models/query.py", line 653, in first
Warning:     for obj in (self if self.ordered else self.order_by('pk'))[:1]:
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
Warning:     self._fetch_all()
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
Warning:     self._result_cache = list(self._iterable_class(self))
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
Warning:     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
Warning:     return list(result)
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1554, in cursor_iter
Warning:     for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1554, in <lambda>
Warning:     for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/db/utils.py", line 96, in inner
Warning:     return func(*args, **kwargs)
Warning:   File "/opt/yunohost/pyinventory/venv/lib/python3.7/site-packages/django/db/backends/postgresql/utils.py", line 6, in utc_tzinfo_factory
Warning:     raise AssertionError("database connection isn't set to UTC")
Warning: AssertionError: database connection isn't set to UTC
Warning: [Error] Upgrade failed.
```

**Comment by jedie** [comment]
fixed by https://github.com/YunoHost-Apps/pyinventory_ynh/commit/ae1f3cdcf5af9bf6101f94a8e0823131ee02c56f
